### ISSUE TITLE
Take Note If/When Building a CentOS Docker Host

### ISSUE THREAD

**Issue by McFateM** [Islandora-Collaboration-Group/ISLE#101]
When creating a CentOS host the default filesystem is now XFS.  XFS out-of-the-box has known, but very transient, issues with Docker.  In our case, my Dockerized icg_web_test was unable to open web resources inside our campus firewall, a problem I could not repeat on other nodes.  The problem was our new CentOS Docker platform was built with XFS and the d_type (directory type setting) was NOT overridden.  In the end we had to rebuild the CentOS 7 host from scratch and specify it with an EXT4 filesystem.  All problems solved.

I didn't use the following resource when researching/fixing our problem, but this seems like it might be a useful reference:  https://community.centminmod.com/threads/using-docker-on-centos-7-choose-ext4-over-xfs.12492/

**Comment by marksandford** [comment]
Is this still an issue?  I haven't heard it cropping up recently?

**Comment by SummittDweller** [comment]
Fixing this a little over a year ago with our CentOS builds was a MAJOR bump in the road for me.  I hope it's mentioned somewhere in our docs, perhaps an appendix or "cookbook" entry?  

If there is a CentOS specific portion of our docs I think that should at least point to https://docs.docker.com/storage/storagedriver/overlayfs-driver/.  Looking there, it doesn't appear that this has been "resolved" inside Docker, they just still caution that it may be an issue for some host filesystems.
