### ISSUE TITLE
Docker Networking:  implement proxy container and define docker networks

### ISSUE THREAD

**Issue by br2490** [Islandora-Collaboration-Group/ISLE#103]
I would like to see some development around this.  It deprecates the need for editing your "etc/hosts" or adding "extra_hosts" - please see latest bcol migration compose for working example -
 granted this was done without some documentation so it may need a fewwwwwww tweaks.
  (https://github.com/BarnardArchives/barnard_isle_docker) 

I'll also leave the result of this example migration on/up for the day at http://belle.benjaminrosner.com (it's just a VM on my workstation doing this).  There are still a few things to note as issue - like some proxying of services up to the user layer (looking at you djatoka) - 

I'm wondering if in the next stages we could create a small NGINX proxy to sit in front of the entire stack - and on the only docker publicly-accessible network - so that all comms go through NGINX.   It could be secure with certs.  I wonder if that also means there is additional opportunity to "load balance" with containers (i.e., roundrobin the heck of out multiple instances of the same container in nginx).  So many possibilities I LOVE IT!

DEVEL:
- [x] delineation between an internal and external network, where `internal` is only accessible to the stack itself, and `external` is for wide access.  this is 
- [x] add a new service.  Maybe called `proxy` for testing and name TBD later.
  - [x] use image NGINX:LATEST 
  - [x] generate generic service-level definition of all stack components as `upstream`s (LB)
  - [x] proxy routes for services required for external visitors
- [x] On image isle-apache:
  - [x] create generic isle and isle-ssl confs.

TEST:
- [x] certs
- [ ] cert bot
- [ ] snakeoil to secure intra-stack comms too? meh.
- [ ] security

A test instance is running at https://belle.benjaminrosner.com
nb: fgs still will not load, so the stack is incomplete in the truest sense, but the site works, fedora, solr, etc.

**Comment by g7morris** [comment]
@br2490 This is something I've been thinking about for awhile now re NGINX proxy. I'm wondering how much could be gained by using something like this https://traefik.io/ (nginx proxy designed for these type of setups) Do you know anything about it? I'm curious what benefits it could have for SSL, Djatoka etc. and helping to better route things in general.

**Comment by McFateM** [comment]
My $0.02….  Traefik and Nginx are bedrock elements of the docker4drupal stuff that I’ve been playing with lately.  I’m sure I don’t understand it fully, and I have not tried applying either to ISLE, nor have I done any SSL work in Nginx yet, but I really like what I’ve seen in docker4drupal thus far.  I have successfully applied d4d to building a Dockerized version of two Drupal 8 sites that I develop and maintain.  Can’t say it’s better than Apache and vhosts, but it’s certainly not worse.  In my own experience, Apache + Vhosts = potential for headaches and TROUBLE.  And SSL just exacerbates that.  Traefix and Nginx have been virtually trouble-free for me thus far.

-Mark M.

**Comment by br2490** [comment]
Status: in development
need early review @McFateM @g7morris if https://belle.benjaminrosner.com/ && http://belle.benjaminrosner.com/ work as expected externally 

Development thoughts

- [ ] delineation between an internal and external network, where `internal` is only accessible to the stack itself, and `external` is for wide access.  this is 
- [ ] add a new service.  Maybe called `proxy` for testing and name TBD later.
  - [ ] use image NGINX:LATEST 
  - [ ] generate generic service-level definition of all stack components as `upstream`s (LB)
  - [ ] proxy routes for services required for external visitors
- [ ] On image isle-apache:
  - [ ] create generic isle and isle-ssl confs.
- [ ] @g7morris could you note additional areas that should be coming through this proxy that are currently proxied via something apache in the stack?  I have a definition for SOLR but that's actually just an internal-to-the-stack service, right?

hitlist
- [x] add stack network, add all services.
- [x] public ingress network created and proxy added to it
- [x] ports 80, 443 exposed; opened on router.
- [x] SSL certs (oh goodness)
- [x] generalized configs for apache; nginx config to proxy upstreams for apache, fedora, solr (unused).
- [x] TEST RUNNING

The development proxy container is running - 17 FEB 2018 noonish.

**Comment by br2490** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=belle.benjaminrosner.com for default ciphers? @hamhpc @g7morris

**Comment by br2490** [comment]
@g7morris see our [repo](https://github.com/BarnardArchives/barnard_isle_docker) for working example.  

I updated the readme but it is still out of date -- it doesn't mention the proxy, certificates, etc.  However the docker-compose is rather simple for the proxy.  

Now would be the time to get letsencrypt bot going (#44)

Also circling back to Diego and caching responses from loc.gov (or sorry, whatever the correct address is for validation) should be implemented here.  network alias the proxy to the appropriate URL, create a proxypass to the real site, set a cache of X duration, rinse, repeat.  Or just serve them statically (i'm not a lawyer)

@g7morris we should absolute chat about how this works, and all.

**Comment by g7morris** [comment]
@br2490 I think this ticket can be closed no? Aren't we doing all this now?
