### ISSUE TITLE
Per #97 FGS will not start

### ISSUE THREAD

**Issue by br2490** [Islandora-Collaboration-Group/ISLE#104]
Fedora GSearch will _not_ load on a physical Ubuntu host.

#97 is specific to Macs
This ticket extends that, and requests review

**Comment by br2490** [comment]
The discussion in #97 totally resolves this.  Removing the duplicate logging library in FGS `log4j-over-slf4j-1.5.10.jar` and FGS is logging and running!  many thanks again to Diego Pino for this 🌟

**Comment by g7morris** [comment]
Closing ticket as issue has been resolved with the removal of that jar file (mentioned above), new images have been built and the changes to code merged into master.
