### ISSUE TITLE
Fedora Image: dedupe JDKs

### ISSUE THREAD

**Issue by br2490** [Islandora-Collaboration-Group/ISLE#105]
Some thoughts about the size of some Docker images:

I think the Fedora image using the **correct** Tomcat Docker is installing two versions of Java, the one we desire (shall not say their name), and one we might not need?  Maybe we can slim the image by stopping this - the layer is rather large on a running container (~403.5 megabytes).

FROM TOMCAT Docker File
```
RUN set -ex; if [ ! -d /usr/share/man/man1 ]; then mkdir -p /usr/share/man/man1; fi; apt-get update; apt-get install -y openjdk-8-jre="$JAVA_DEBIAN_VERSION" ca-certificates-java="$CA_CERTIFICATES_JAVA_VERSION" ; rm -rf /var/lib/apt/lists/*; [ "$(readlink -f "$JAVA_HOME")" = "$(docker-java-home)" ]; update-alternatives --get-selections \| awk -v home="$(readlink -f "$JAVA_HOME")" 'index($3, home) == 1 { $2 = "manual"; print \| "update-alternatives --set-selections" }'; update-alternatives --query java \| grep -q 'Status: manual'
```
if my interpretation of this line is correct, I believe this RUN layer is checking for a directory, if it isn't found it installs OpenJDK.   Maybe creating this folder and recreating the image will prevent the **correct** tomcat image from installing what we don't need.  If that doesn't work the second easiest is just `apt remove --purge ...`

I will look at the TOMCAT Dockerhub page and see if there is any mention of using alternative JDKs and update ticket on what I find.

**Comment by g7morris** [comment]
Both Java images are needed for tools like maven and ant (OpenJDK) and Oracle Java is mandatory for  running djatoka on both the Fedora and Apache containers.  Both are required and I've run into issues on non ISLE builds by not using OpenJDK with maven. bit of a chicken and egg thing. I'm going to recommend that this be something to pursue potentially with more testing and development in ISLE Phase II.

**Comment by br2490** [comment]
This has been resolved in the refactored images; isle-tomcat base only has Oracle's JDK and all components work including mavin/ant/djatoka/etc.
