### ISSUE TITLE
Clarify Ansible working directory

### ISSUE THREAD

**Issue by ctgraham** [Islandora-Collaboration-Group/ISLE#107]
We say `cd /path/to/ISLE/repo` before running the ansible test, but we really mean something like `cd /path/to/ISLE/repo/ansible/`.

https://github.com/Islandora-Collaboration-Group/ISLE/blame/6d8a4760ed8a0e738daea49e5f0776fe3200078b/docs/1_system_process_overview/1_4_testing/host_server_setup_ansible.md#L238

This also occurs in host_remote_setup_ansible.md
https://github.com/Islandora-Collaboration-Group/ISLE/blob/9b0117a73fb9f9a79ba331f148081e5c8cd84068/docs/1_system_process_overview/1_4_testing/host_remote_setup_ansible.md

**Comment by br2490** [comment]
Thank you @ctgraham!

Notes to the assignee/team, these documents are now located@repo: https://github.com/Islandora-Collaboration-Group/ISLE-Documentation/tree/master/docs/1_system_process_overview/1_4_testing

**Comment by g7morris** [comment]
@br2490 Thanks for circling back on this with the correct modified doc. Closing ticket as original documentation has been modified accordingly.
