### ISSUE TITLE
Add granular/line indicies to each document

### ISSUE THREAD

**Issue by McFateM** [Islandora-Collaboration-Group/ISLE#114]
I'm running into far too many interruptions to work though the new migration guide in a single pass, and I'm confused by some things along the way too.  So, I'd like to suggest considering addition of a "chapter and verse" granularity to the docs so that I (anyone) can more easily track where they are when they are interrupted, and more importantly, so that we can discuss the documents intelligently without having to reconcile which portion we are dealing with.  After all, line numbers will change, perhaps quite often.

Below is one portion of the migration_guide.md with a proposed numbering scheme...

``
### 2 - Migration to ISLE Process Overview

As this is a large guide, here's a quick not very detailed overview of what's going to happen in the next steps:

* 2.1 - Ensure that the destination ISLE host server has the same (or more) amount of storage as the production server.
* 2.2 - Create appropriate Islandora Production data storage structure on new ISLE host server
* 2.3 - Copy current production data and config files as directed by the [export checklist](migration_export_checklist.md) to an appropriate location on the new ISLE host Server.
* 2.4 - Create the required new config directory by copying the template `/opt/ISLE/config/isle-prod-project.institution` to a renamed directory within `/opt/ISLE/config`
* 2.5 - Compare the template settings within the new renamed directory of `/opt/ISLE/config/enduser-renamed-directory.institution` to the current production config files. Merge or edit as necessary in the new isle config directory for use with ISLE.
   * 2.5.1 - There may be some additional work to compare and merge in previous enduser customizations of the Solr `schema.xml` to the new ISLE config.
   * 2.5.2 - There may be some additional work to compare and merge in previous enduser customizations of the Solr `solrconfig.xml` to the new ISLE config.
   * 2.5.3 - There may be some additional work to compare and merge in previous enduser customizations of the Solr `stopwords` to the new ISLE config.
   * 2.5.4 - There may be some additional work to compare and merge in previous enduser customizations of the Islandora Transform (XSLTs) files to the new ISLE versions.        
* 2.6 - Based on new paths, edit the `docker-compose.yml` file to
   * 2.6.1 - Point to the new associated `islandora_production_data_storage` structure.
   * 2.6.2 - Point to the new directories and config settings in `/opt/ISLE/config/enduser-renamed-directory.institution`
* 2.6.3 - Spin up new containers one at a time with the new config settings
* 2.6.4 - Check that all services are running properly
* 2.6.5 - Repeat entire process (_if necessary_) for additional ISLE environments e.g. _production, staging and development_

**Comment by dwk2** [comment]
I like the direction of providing an overview such as this example. 
The idea of "chapter and verse" would be to include hyperlinks to walk a person through the steps from 2.1 all the way to 2.65, yes?

**Comment by McFateM** [comment]
I wasn't thinking of links, but that would certainly be possible.  I'm looking more for the ability to:
1) make a note that I stepped away (all too often) at line 2.6.4 in the mingration_guide.md, for example, or
2) so that you and I could more easily collaborate on the differences between sections 3.2.1 and 4.4.1, a real-world example in my case (of course that assumes we all have the same numbering of lines).

**Comment by hamhpc** [comment]
It would also be great to include this numbering on all the pages as well?
It looks like the docs started that way with the directory names (ie.
1_4_testing) but then the files in those directories are all just names.
It's hard to tell looking at the repo pages what order they should go in.
This was what was hard to decipher from trying to look at this within the
repo when this was a separate branch from the master.

-Steve


*****************************************
Steven L. Young
Unix/HPC System Administrator
Hamilton College
*****************************************

**Comment by McFateM** [comment]
Ultimately I’d love to see a structure so that I could make a note that…

  “doc:1.4:2.4.3 is where I left off", or
  “doc:2.6:1.3.3.1 needs attention”.

This implies that each document has a reference number, and each has a granular numbering of the paragraphs/bullets/headings within.  Trick is keeping things up-to-date, and not making the structure too cumbersome.
