### ISSUE TITLE
ISLE on Windows

### ISSUE THREAD

**Issue by br2490** [Islandora-Collaboration-Group/ISLE#133]
Placeholder for what we've learned; will likely breakout in to several issues which will reference back.

**Comment by LibraryIT** [comment]
I used a Windows 10 laptop and have been taking notes as I went along and can post more later.  My approach has been to spin up a development environment using vagrant and virtualbox.  It may be possible to use Hyper-V or Docker for Windows.

Overall the instructions for Macs seem to be mostly portable.  Basically one must install virtualbox, the virtualbox extensions, and vagrant.  Once the VM has been created, one can enter it and follow the standard CentOS instructions.

**Comment by LibraryIT** [comment]
Here are my instructions for installing ISLE on Windows.
[isle for windows dev.txt](https://github.com/Islandora-Collaboration-Group/ISLE/files/1804536/isle.for.windows.dev.txt)

**Comment by g7morris** [comment]
The documentation for:

1) Docker for Windows is here https://islandora-collaboration-group.github.io/ISLE-Documentation/01_installation_host_server/install_docker_for_windows/

2) installing ISLE please start here https://islandora-collaboration-group.github.io/ISLE-Documentation/install_start_here/

Closing ticket as this documentation was created from efforts during the Metro Hack / Doc. If there are issues with documentation, please file new tickets with. Additionally submitting new potential instructions for other windows configurations are always appreciated in the form of pull requests for the ICG steering committee to review. Thanks for all the help and insight!
