### ISSUE TITLE
Remove Binaries from containers

### ISSUE THREAD

**Issue by dmer** [Islandora-Collaboration-Group/ISLE#15]
binary installers and jar files like gsearch and fedora will be replaced in the container code with external downloads in the proper Dockerhub style

**Comment by g7morris** [comment]
I've removed all binaries associated with the install process.

**Comment by g7morris** [comment]
From convo with @dmer 

- Remove all drupal folders

- New Sample repo: Create a site folder with drush.sh includes drupal & islandora makefile process (missing currently) 

- Current ISLE repo: Within site folder create a commented out version of drush.sh that mirrors new sample but no specific values

**Comment by g7morris** [comment]
One more point: Use official Dockerhub image user names and passwords. 

Also investigate generic database name of drupal7 and fedoraAdmin generic passwords (if possible)

**Comment by g7morris** [comment]
This issue can now be closed due to use of new official images in Solr and Fedora Dockerfiles along with multi-build process in web. The master branch of the project will be the sample site. no separate repos.
