### ISSUE TITLE
Failed ability to edit MODS datastream for PDF object in local ISLE

### ISSUE THREAD

**Issue by dwk2** [Islandora-Collaboration-Group/ISLE#150]
I'd like to know if other institutions have had success with this issue that is failing for our ISLE instance. Not sure if this is a result of our MODS differing in structure from the default schema.xml currently loaded, as opposed to our older and customized schema.xml. Comments, feedback welcome.

Failed Test to edit MODS datastream for PDF object. Example below:
Login, view this object URL
(https://isle-dev.williams.edu/islandora/object/studenttheses%3A1107#)
click: Manage
click: Datastreams
MODS -> Edit
Resultant error page
Failed to find document http://www.loc.gov/standards/mods/v3/mods-3-4.xsd
(https://isle-dev.williams.edu/islandora/object/studenttheses%3A1107#overlay=islandora/edit_form/studenttheses%253A1107/MODS)

**Comment by patdunlavey** [comment]
Hi David, On first impression, this does not seem to be an ISLE platform issue, but I'd be interested in learning if others can replicate this problem.

**Comment by br2490** [comment]
Superseded by #167
