### ISSUE TITLE
Upon deploy, access denied to View Islandora Objects

### ISSUE THREAD

**Issue by bgilling** [Islandora-Collaboration-Group/ISLE#151]
After looking at XACML policies for over an hour and debugging that they were (finally) not what was forbidding access to the objects when I logged out, I remembered that the Drupal permission for "Islandora" "View repository objects" might be preventing access... embarrassed to say that I did not look here sooner because assumptions usually.

Could the "install_isle_ld_site.sh" setup script automatically set this permission to allow "View repository objects" for anonymous users? *(similar to how the islandora_paged_content_gs is set)

If not, can this be added to the documentation in 48 pt. bold red font?

**Comment by br2490** [comment]
added drush rap 'anonymous user' 'view fedora repository objects' to script.

**Comment by bgilling** [comment]
Ben -- no worries whatsoever.  I have been too busy to even remember.  Feel free to close the issue unless it has to be attached to a git changeset.

**Comment by br2490** [comment]
Resolved in https://github.com/Islandora-Collaboration-Group/isle-apache/commit/88bfafd7b1981ae4cae07bc33e4fe7b07c38de9d
