### ISSUE TITLE
Automatic Certificate Generation

### ISSUE THREAD

**Issue by br2490** [Islandora-Collaboration-Group/ISLE#154]
With Traefik, add in and document:
https://docs.traefik.io/user-guide/examples/#lets-encrypt-support

**Comment by g7morris** [comment]
@br2490 @marksandford I'll be testing this process on the Colgate Staging server shortly.

**Comment by bseeger** [comment]
Is this issue solved by the above commit by Mark, or does more need to be done here?   Was there documentation written to address this?  

Thanks!

**Comment by SummittDweller** [comment]
I have successfully engaged Let's Encrypt on a number of fronts with Traefik, but I don't recall if I specifically used the subject document in my work.  I'm also approaching an opportunity to engage it again in staging and if/when that happens I can possibly review the document and see if it matches what I've done and comment on any differences.

**Comment by marksandford** [comment]
I believe this can be closed.  If there's still a problem with the documentation, it should be an issue in the docs repo, not here.
