### ISSUE TITLE
Add in SSHD to ISLE-Apache

### ISSUE THREAD

**Issue by br2490** [Islandora-Collaboration-Group/ISLE#155]
Per @dwk2 please add in SSHD for the Apache container

- [ ] install openssh-server
- [ ] S6 management of openssh
- [ ] Add generic password to Islandora user
- [ ] Create volume area to mount user SSH keys

**Comment by br2490** [comment]
@DiegoPino Your point is well taken and you are correct that there is little need for running OpenSSHD - just adds a layer and megabytes.  

If I had to take a guess, I think it may just be the familiarity of SSH and working that way - so I'm not opposed to adding it in at all.  Especially for those less familiar with docker it may offer an easier transition.

I believe the request was from the original ISLE and so @dwk2 might be able to expand on this.

**Comment by g7morris** [comment]
Closing this ticket as openssh isn't a requirement anymore and we are well past 1.2 in releases. If someone needs `openssh` or other features above, please reopen this ticket or create a new one. Thank you.
