### ISSUE TITLE
CONFD and Configuration of Daemons

### ISSUE THREAD

**Issue by br2490** [Islandora-Collaboration-Group/ISLE#157]
Using CONFD please parse ENV_VARs (from .env file) into their appropriate containers and locations. Create new ENVVARS for missed variables.

https://github.com/kelseyhightower/confd
Resources: http://www.mricho.com/confd-and-docker-separating-config-and-code-for-containers/, https://golang.org/pkg/text/template/

**Comment by br2490** [comment]
This has been moved to the 1.1 release and as such remains opened for UAC/QA.
All vars are in .env (a comprehensive list of variables to set passwords, site-name, etc.) and tomcat.env (to set daemon user/pass on all instances of tomcat).
We may decide to create more <named>.env files to clarify the process but one file to rule them, or many files to rule them: that's up to the users to decide (and I guess us, but really them).

**Comment by g7morris** [comment]
This is now a feature in ISLE and can be closed.
