### ISSUE TITLE
Test build on Linux sever

### ISSUE THREAD

**Issue by dmer** [Islandora-Collaboration-Group/ISLE#16]
using a temporary linux server on Digital Ocean to weed out the Docker-for-Mac specific issues to get the containers able to run on a linux environment

ISLE Steering Committee testers will be given access to this server

**Comment by g7morris** [comment]
Please test/fix the following new updates for this ticket/process:

- use new ISLE sample Git repo for build

- [Remove Binaries from containers](https://github.com/Islandora-Collaboration-Group/ISLE/issues/15)

- Test [Use Dockerhub Tomcat 8.x image](https://github.com/Islandora-Collaboration-Group/ISLE/issues/17)

- Test [Use Dockerhub Apache image](https://github.com/Islandora-Collaboration-Group/ISLE/issues/18)

- [Update openseadragon unzip process in 1.4 testing - Alpha build guide](https://github.com/Islandora-Collaboration-Group/ISLE/issues/19)

- [Update Drupalfilter to 7.19 not 7.13](https://github.com/Islandora-Collaboration-Group/ISLE/issues/20)

- [Update FITS from 1.04 to 1.20](https://github.com/Islandora-Collaboration-Group/ISLE/issues/22)

**Comment by g7morris** [comment]
This issue can be closed. Tested on Digital Ocean Ubuntu 16.04 LTS server and passed. http://islandora-docker.com is a real working domain for this test.
