### ISSUE TITLE
Unable to view/login to the Tomcat admin panel for solr container

### ISSUE THREAD

**Issue by g7morris** [Islandora-Collaboration-Group/ISLE#163]
#### Issue description

Upon creation of a New ISLE site, following the requirements of the ISLE 1.1. RC Testing Matrix https://docs.google.com/spreadsheets/d/1L-wrivXq2pUz7vcGsMCx3X7yKf27uokoaR8SovU_BsU/edit#gid=0, I am unable to login to the Tomcat admin panel for solr container despite entering both the admin and manager passwords. 

#### Steps to reproduce the issue

1.  Create new ISLE site
2. Attempt to login to Login to the newly created solr Tomcat admin panel (in my case,http://islandora-docker.com:8082/manager/html)

#### What's the expected result?

- That I would see the solr Tomcat admin panel and be able to click on the Solr webapp settings etc.

#### What's the actual result?

- The prompt reappears empty as if I didn't enter any information in essence rejecting my username and password. 

#### Additional details / screenshot

- All containers running tomcat i.e. `fedora, solr, image-services` all use the same `tomcat.env`

- Only the fedora Tomcat admin panel allows access. The solr & image-services Tomcat admin panels do not.

**Comment by br2490** [comment]
Resolved by https://github.com/Islandora-Collaboration-Group/isle-solr/pull/1

**Comment by g7morris** [comment]
Thank you for the fix however for testers it would be appreciated if a next steps response would be posted when necessary. In this case, I think for those getting onboarded with ISLE, they'd potentially need it. 

In this instance, would it be fair to assume I need to first:

* `docker-compose stop` to stop all running containers

* delete my current containers, `docker rm isle-solr-id` etc

* `docker pull` the `image-services` image 

* `docker-compose up -d`

Resume testing for this situation and confirming that the issue has ceased. If resolved, leave the ticket closed, if not reopen.

**Comment by br2490** [comment]
Noted, thanks.  

to continue your testing:
- `docker-compose pull`
- `docker-compose up -d`

The containers are ephemeral and can be updated with above commands, you are not required to `down` or `rm`.

**Comment by g7morris** [comment]
@br2490 Hmm following the commands above as directed. 

`docker-compose pull`

```
Pulling isle-portainer ... done
Pulling mysql          ... done
Pulling solr           ... done
Pulling fedora         ... done
Pulling traefik        ... done
Pulling apache         ... done
Pulling image-services ... done

docker-compose up -d

Starting isle-proxy-id       ... error
Recreating isle-mysql-id ...
Recreating isle-portainer-id ...
Recreating isle-mysql-id     ... done
Recreating isle-portainer-id ... done
Recreating isle-solr-id      ... done
Recreating isle-fedora-id    ... done

ERROR: for traefik  Cannot start service traefik: driver failed programming external connectivity on endpoint isle-proxy-id (c44bc90d8293bd602b8a2edf0030af474d57192874bebd9b0e0c908faa70fa3f): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use
ERROR: Encountered errors while bringing up the project.
```

**Comment by g7morris** [comment]
@br2490 Found it. Apologies for false alarm. Further digging revealed a service that was interfering on host server. Not related to ISLE.

**Comment by g7morris** [comment]
Confirmed as fixed. Access granted on this container.

**Comment by br2490** [comment]
Something on the host machine is already using port 443.  `docker ps` and
see if you can see any containers that are running using 0.0.0.0:443->443;
if so, please use `docker stop {container_name or hash}`
If running *nix/mac: `lsof -i :443` to find applications otherwise, and you
may use (Ubuntu) `stop {application_name}`, (Debian/RHEL/CENTOS/Mac)
`killall {application_name}` or using (all *nix, incl. mac) `kill
{application_PID}` (to find pid use `ps aux | grep {application_name}`

Best,
Ben

Benjamin Rosner

Instructional Application Developer
Instructional Media and Technology,
Barnard Library and Academic Information Services
p: 212-854-9005
