### ISSUE TITLE
Unable to view/login to the Tomcat admin panel for image-services container

### ISSUE THREAD

**Issue by g7morris** [Islandora-Collaboration-Group/ISLE#164]
#### Issue description

Upon creation of a New ISLE site, following the requirements of the ISLE 1.1. RC Testing Matrix https://docs.google.com/spreadsheets/d/1L-wrivXq2pUz7vcGsMCx3X7yKf27uokoaR8SovU_BsU/edit#gid=0, I am unable to login to the Tomcat admin panel for image-services container despite entering both the admin and manager passwords. 

#### Steps to reproduce the issue

1.  Create new ISLE site
2. Attempt to login to Login to the newly created solr Tomcat admin panel (in my case,http://islandora-docker.com:8083/manager/html)

#### What's the expected result?

- That I would see the image-services Tomcat admin panel and be able to click on the Cantaloupe webapp settings etc.

#### What's the actual result?

- The prompt reappears empty as if I didn't enter any information in essence rejecting my username and password. 

#### Additional details / screenshot

- All containers running tomcat i.e. `fedora, solr, image-services` all use the same `tomcat.env`

- Only the fedora Tomcat admin panel allows access. The solr & image-services Tomcat admin panels do not.

**Comment by br2490** [comment]
Resolved by a rebuild of container as the base it was original built on was out-of-date.
No code change required.

Thank you for reporting.

**Comment by g7morris** [comment]
Thank you for the fix however for testers it would be appreciated if a next steps response would be posted when necessary. In this case, I think for those getting onboarded with ISLE, they'd potentially need it. 

In this instance, would it be fair to assume I need to first:

* `docker-compose stop` to stop all running containers

* delete my current containers, `docker rm isle-imageservices-id` etc

* `docker pull` the `image-services` image 

* `docker-compose up -d`

Resume testing for this situation and confirming that the issue has ceased. If resolved, leave the ticket closed, if not reopen.

**Comment by br2490** [comment]
Noted, thanks.  

to continue your testing:
- `docker-compose pull`
- `docker-compose up -d`

The containers are ephemeral and can be updated with above commands, you are not required to `down` or `rm`.

**Comment by g7morris** [comment]
@br2490 Confirmed as fixed. Access granted on this container. As a bonus side note, can see Cantaloupe admin panel. Awesome! Thanks.
