### ISSUE TITLE
Please create a local cache of LOC.gov

### ISSUE THREAD

**Issue by br2490** [Islandora-Collaboration-Group/ISLE#168]
If possible please create and redirect all container traffic to a cached copy of LOC.gov's data used for validation.
Additionally set a reasonable check time for updates, like every two weeks?

**Comment by bseeger** [comment]
Can someone clarify (flesh out) this more?  Are we talking subject headings and the likes from LOC.gov?    What datasets specifically?   These data sets, depending on which ones, can be huge.  But maybe I'm misunderstanding this. 

Thanks!

**Comment by SummittDweller** [comment]
I don't recall all the specifics on this, but I think it was based on work that Diego has done.  Maybe have a look in the forums for his work related to this, or we could reach out to him directly?

**Comment by marksandford** [comment]
If I recall correctly, generating HOCR required validation against a schema on loc.gov, which was pulled from the loc server for each page ingested, causing a bottleneck.  Diego had a fix that involved caching it locally and using (I believe) the hosts file and apache config to serve the files locally.

**Comment by marksandford** [comment]
More details from Diego: https://groups.google.com/forum/#!topic/islandora/4F5oKDI5CEE

**Comment by dwk2** [comment]
And to add to what Mark S said: My memory is that the idea of caching this
file on a weekly (give or take) basis was to ensure that we our locally
cached file remains up to date even if the LOC.gov updates their file.

David Keiser-Clark

**Comment by g7morris** [comment]
This is now a feature in ISLE https://github.com/Islandora-Collaboration-Group/ISLE/blob/main/docs/optional-components/loc-proxy.md closing ticket.
