### ISSUE TITLE
Looking for takers: update Ansible!

### ISSUE THREAD

**Issue by br2490** [Islandora-Collaboration-Group/ISLE#169]
Dear all,

Anyone with Ansible expertise is welcomed and invited to update the current scripts to reflect recent changes and deployments.

Shamelessly tagging @g7morris and @McFateM 

Thank you!

**Comment by g7morris** [comment]
No problemo. I'll make a pull request for changes next week for Ubuntu related things.

**Comment by g7morris** [comment]
This has been completed and is a recurring task for maintainers. Closing ticket
