### ISSUE TITLE
Use Dockerhub Tomcat 8.x image

### ISSUE THREAD

**Issue by dmer** [Islandora-Collaboration-Group/ISLE#17]
-test for Fedora
-test for Solr

**Comment by g7morris** [comment]
Currently using ubuntu 14.04 apt package for tomcat7. Please investigate using official Docker Hub image from https://hub.docker.com/_/tomcat/ upgrade to version 8 as well.

**Comment by g7morris** [comment]
This issue can be closed. Solr and Fedora images/containers are now officially using Tomcat 8 images straight from apache.
