### ISSUE TITLE
Migration script changes for Drupal

### ISSUE THREAD

**Issue by br2490** [Islandora-Collaboration-Group/ISLE#170]
This script should run in the migration script here, https://github.com/Islandora-Collaboration-Group/ISLE-Drupal-Build-Tools/blob/master/migration_site_vsets.sh

sed settings for /var/www/html/sites/default/settings.php and sites/*/settings.php:
Database section:
- [ ] update 'host' => 'mysql'
- [ ] update 'username' => {DRUPAL_DB_USER}
- [ ] update 'password' => {DRUPAL_DB_PASSWORD}
- [ ] update 'port' => '3306' (or set it as '')
- [ ] check and possibly update/set (need to verify ramifications if this was _not_ original set)
  - [ ]  'charset' => 'utf8mb4'
  - [ ] 'collation' => 'utf8mb4_general_ci'

Drupal vsets:
All good but issues may arise:
Check on current vsets that set solution pack viewers so that they do not overwrite existing settings.
e.g., Barnard has additional viewers installed for newspaper/book/pdf solution packs.

writing this as going through migration. will update as needed. (also sick, so if anything comes of poorly it's lack of cognitive facility)

**Comment by g7morris** [comment]
This is now a feature in ISLE and actively maintained
