### ISSUE TITLE
Deprecate fix-attribs for ISLE-Fedora and potentially ISLE-Apache

### ISSUE THREAD

**Issue by br2490** [Islandora-Collaboration-Group/ISLE#171]
On boot the fix-attribs script that is part of S6 overlay takes an inordinate amount of time.
Consider alternatives or check if this is a local issue.

**Comment by br2490** [comment]
So this was deprecated on Fedora, especially the data folder, but the moment drop-privelleges is enabled and tomcat is running as `tomcat`, not `root` there will be issues.  It might be worth a simple script that bypasses S6 and uses native chown tomcat:tomcat and makes sure `-type d chmod 755` and `-type f chmod 644` 
tagging @g7morris

**Comment by bseeger** [comment]
With the commit described above, is this issue solved?  If so, can we close?  Thanks!

**Comment by g7morris** [comment]
This issue has not been solved per se. The comment above `On boot the fix-attribs script that is part of S6 overlay takes an inordinate amount of time.` is still relevant. I think we should review this as part of an upcoming ISLE release.

**Comment by g7morris** [comment]
This feature is going to be pulled from the ISLE-apache image and will be manually run only. Closing ticket.
