### ISSUE TITLE
Set adore-djatoka to use internal routing

### ISSUE THREAD

**Issue by br2490** [Islandora-Collaboration-Group/ISLE#174]
- [x] Update the mod rewrite directive to:
```
        RewriteEngine On
        RewriteCond %{QUERY_STRING} (.*)(https|http)(?:[^%]|%[0-9A-Fa-f]{2})+(%2Fislandora.*)
        RewriteRule ^/adore-djatoka/resolver /adore-djatoka/resolver?%1http://apache%3 [L,PT]
```

**Comment by br2490** [comment]
In development, commit https://github.com/Islandora-Collaboration-Group/isle-apache/commit/930f43c8b6a2409250d812f030696d4659cac33b.

**Comment by g7morris** [comment]
@br2490 So in essence we're no longer using https / SSL with adore-djatoka ? If the move to Cantaloupe has been made, the only use for `adore-djatoka` would be its `kakadu` libraries for creating and decompressing (_reading_) JP2s etc.

**Comment by br2490** [comment]
In essence this just routes adore-djatoka like Cantaloupe's delegates files routes.  The query is rewritten directly back to apache rather than whatever BASE_DOMAIN is.
Still supportin both AD and IIIF.
