### ISSUE TITLE
Use Dockerhub Apache image

### ISSUE THREAD

**Issue by dmer** [Islandora-Collaboration-Group/ISLE#18]
-test for web

**Comment by g7morris** [comment]
Currently using ubuntu 14.04 LTS apt package method for Apache 2.4. 

Investigate using http from Dockerhub instead https://hub.docker.com/_/httpd/

**Comment by g7morris** [comment]
This issue can now be closed. Decision was made not to use this version due to version clashes and potential use of PHP7. Used multi-build process instead and kept using ubuntu14.04 official image. Perhaps in a future build post project.
