### ISSUE TITLE
Solr Image - ICUFoldingFilterFactory values for indexing diacritics missing from schema.xml

### ISSUE THREAD

**Issue by g7morris** [Islandora-Collaboration-Group/ISLE#186]
#### Issue description

On the current Solr Image, ICUFoldingFilterFactory values for indexing [diacritics](https://en.wikipedia.org/wiki/Diacritic) are missing from schema.xml. This will mean potentially improper or missing necessary indexing of any object with accents, symbols etc in it's metadata.

Given that the necessary SOLR libraries are indeed installed https://github.com/Islandora-Collaboration-Group/isle-solr/blob/27c1dc649d0d296af37db38c3e82539e4a427e86/Dockerfile (_see lines 37 & 38_), this should hopefully be easy to fix by adding in the appropriate lines to the `schema.xml` file. 

#### TO DO / Steps to resolve the issue

* Review https://github.com/discoverygarden/basic-solr-config/blob/4.10.x/conf/schema.xml

* Review Example attached [schema_with_icu.txt](https://github.com/Islandora-Collaboration-Group/ISLE/files/2511712/schema_with_icu.txt). I've commented in the appropriate areas with `<-- ISLE customized 2018 -->`

* Determine how during the Solr image build process, to add / append etc the following:

  * Between the current Lines 164 and 165  add:  `<filter class="solr.ICUFoldingFilterFactory"/>` 

  * Between the current Lines 173 and 174 add:  `<filter class="solr.ICUFoldingFilterFactory"/>`

@br2490 I'll leave it to you how this process should work in the [Dockerfile](https://github.com/Islandora-Collaboration-Group/isle-solr/blob/27c1dc649d0d296af37db38c3e82539e4a427e86/Dockerfile) e.g. use of echo or other tools / methods.

**Comment by br2490** [comment]
@g7morris And line 193 or does that line not get the same treatment?

**Comment by g7morris** [comment]
@br2490 Good question but I don't think so. At least in my experience (_so far_) only the above mentioned lines aka Solr fieldTypes need those extra lines. If endusers need more Solr fieldtypes to be indexed in this manner, they can bind-mount their versions. I'm just after getting a basic out of the box experience.

**Comment by g7morris** [comment]
@br2490 `schema.xml` looks good! Ship it! (_thanks_)

**Comment by br2490** [comment]
Image pushed to Dockerhub as isle-solr:1.1 (default). Please docker-pull and report issues here!  This added the schema.xml version to 1.5 (#185) and diacritics fix per this issue!
This will be incorporated into a large set of changes for publication to the Google Group - testing and feedback please before then, please @g7morris @Islandora-Collaboration-Group/isle-maintainers-commiters-contributors!

**Comment by g7morris** [comment]
@br2490 I'm seeing the changes and will close the ticket. If anyone else finds that diacritics are still not working somehow, please test and open a new ticket.
