### ISSUE TITLE
Update openseadragon unzip process in 1.4 testing - Alpha build guide

### ISSUE THREAD

**Issue by hamhpc** [Islandora-Collaboration-Group/ISLE#19]
I found a couple things in the documentation. First this instruction: 

unzip https://github.com/openseadragon/openseadragon/releases/download/v2.2.1/openseadragon-bin-2.2.1.zip

should just be: 

unzip openseadragon-bin-2.2.1.zip

Then I also think that you need to put in to disable the openseadragon module first before fixing this part. when I tried to enable the module from the instructions it tells me that it was already enabled. So we're fixing openseadragon while the old module is still active. I'm sure it works fine but we might want to disable it first so the enable part works. When I did it it told me it was already enabled. Nothing major.. just a little nit-picky things =).

**Comment by g7morris** [comment]
Thanks @hamhpc I'll be testing this process again to ensure that last step is hopefully unnecessary.

**Comment by g7morris** [comment]
This issue is now closed. Process not required manually. Make_site.sh script takes care of this.
