### ISSUE TITLE
Fedora Image - Saxon and FOP missing?

### ISSUE THREAD

**Issue by g7morris** [Islandora-Collaboration-Group/ISLE#190]
This could be a documentation enhancement request in disguise not an issue but I wanted to confirm a thing or two with @br2490 if possible.

I've noticed that the bundled "[local services](https://wiki.duraspace.org/display/FEDORA34/Fedora+Local+Services)" e.g.  [Saxon](https://wiki.duraspace.org/display/FEDORA34/SAXON+XSLT+Processor+Service) and [FOP](https://wiki.duraspace.org/display/FEDORA34/FOP+Service)  are not being installed anymore in ISLE v.1.1. 

When I review `install.properties` on the Fedora image

* **isle v1.1** https://github.com/Islandora-Collaboration-Group/isle-fedora/blob/f7aa6f9eabcfd586c68278e98b6003a36722d0e3/install_properties/usr/local/install.properties

`deploy.local.services=false`

* **isle v.1.0** https://github.com/Islandora-Collaboration-Group/ISLE/blob/ISLE-v1.0/fedora/fedora/install.properties

`deploy.local.services=true`

---

Can I ask why? Is this a space issue etc?

My current challenge is that I have migrated XSLTs I'd like to validate against a running ISLE system and I'm unable to do so due to these missing services. These services are very handy in the migration process of ISLE. 

@br2490 @marksandford What would you recommend here for ISLE users who are accustomed to having these services bundled?

**Comment by br2490** [comment]
@g7morris  Should we add these back in?  I was following along more closely with our install and the Islandora vagrant.  Let me know and this is a quick rebuild back in and we can call this one done 👍

**Comment by g7morris** [comment]
@br2490 Yeah I think this is a tricky one. On the one hand, having slimmer containers is a positive thing. I also agree that we should be in line to some extent with Islandora vagrant except technically our mandate is "production-ready". There would be those who would argue having these services is good in a production environment. /shrug The hard part is if we keep them then we add to the size, leave them out and there isn't any easy way to get them on the fedora container without rebuilding the image.

**Comment by g7morris** [comment]
I guess if possible leave them in until we hear otherwise. Or perhaps see what the image size is after adding them back in?

**Comment by g7morris** [comment]
@br2490 Has this been updated / pushed?

**Comment by br2490** [comment]
@g7morris Working on it now, will push to as a new Dockerhub image for review and testing! @shauntru if this passes how would you feel about taking this as your first merge/push to DH?

**Comment by br2490** [comment]
@g7morris @shauntru this has been pushed to dockerhub with tag **islandoracollabgroup/isle-fedora:1.dev**.  Please test and report. Increases image size from 656 MB to 719 MB - not a deal breaker IMO.

**Comment by shauntru** [comment]
@br2490 sorry I missed your request above Ben, I'm still trying to ease monitoring GH into my workload, and need to tweak notifications, etc.

**Comment by marksandford** [comment]
Does this still have documentation needs?

**Comment by shauntru** [comment]
> @g7morris Working on it now, will push to as a new Dockerhub image for review and testing! @shauntru if this passes how would you feel about taking this as your first merge/push to DH?

@br2490 Yes, sounds like a plan. When this passes muster I can merge the branch and push the image to DH.

**Comment by g7morris** [comment]
Closing as "fixed" from ISLE 1.5.5 release
