### ISSUE TITLE
Travis CI: associate with ISLE repositories (free for open source)

### ISSUE THREAD

**Issue by dwk2** [Islandora-Collaboration-Group/ISLE#192]
Travis CI is free for open source. Islandora 7x and CLAW both utilize Travis CI, and the ISLE steering committee would like to follow suit and use Travis CI with ISLE. 

Action Item: Need to create a free Travis CI account, and associate (config) to work with the needed ISLE repositories. This is a hosted version, which relieves us of that burden.

* https://github.com/apps/travis-ci
* https://github.com/marketplace/travis-ci/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW43MA==#pricing-and-setup

Timing: This is for ISLE Phase II, so this should occur after the ISLE v1.1 release is final.

**Comment by bseeger** [comment]
@dwk2, @noahwsmith  -  Was this completed with the work Noah just did?   Thanks!

**Comment by g7morris** [comment]
This ticket can been closed as this is an active part of the ISLE maintenance process.
