### ISSUE TITLE
Cantaloupe cache clearing ?

### ISSUE THREAD

**Issue by g7morris** [Islandora-Collaboration-Group/ISLE#207]
#### Issue description
Cantaloupe cache clearing needs attention, fail safes put in place and improvement in ISLE as if left unattended, the ISLE host server disk could be filled to excess.

Source Cache appears to just be a local filestore when the requested image comes from a remote URL:
https://medusa-project.github.io/cantaloupe/manual/4.0/caching.html#Source%20Cache

In our experiments, it does not appear to reuse local files for subsequent requests of the same remote URL, resulting in our Source Cache growing out of control during heavy activity.

```
On Wed, Feb 27, 2019 at 9:56 AM Diego Pino <dpino@metro.org> wrote:
The issue you have there is that caching is happening per URL (not per actual image)
and for every request you get a new URL, the reason is basically a faulty token system
in Islandora to enable temporary access to a protected (or un protected image). 

Solution is quick, don’t pass the token as part of the string, pass it as a header and
use that header to trigger the backend resolving, fetching, etc. Some folks like 
Giancarlo Birello and J.Green go directly to fedora to request the datastream. 

Your use case is a bit more complicated because ICG users totally love embargoes 
and access restrictions, so you need to authenticate somewhere/somehow.

Larger solution would be to check if a datastream is totally public and in that case 
don’t ever bother with token and stuff. But that change requires taping into large
image viewer and the book reader modules.

Also, most of the times you need to hack Islandora to extend the time a token is 
available to at least 6 uses. Warning: whatever you do it will require a full test matrix 
to make sure all works. Like a lot of test objects with different use cases to make sure 
you get it right and moving to the latest Cantaloupe
```

#### For an issue, describe steps to reproduce the issue

System setup (OS information, software versions, etc):

Steps:
1. Setup ISLE v.1.1 
2. Ingest a large set of tiffs (several thousand)
3. Check if disk is saturated

##### What's the expected result?

- Everything "working", tiff objects can be viewed through the openseadragon viewer and tiled by cantaloupe.

##### What's the actual result?

- In many cases server disks are filled to capacity from the `/var/cache/cantaloupe/source` directory. 

- Additional cronjobs and scripts are needing to be used to keep things stable:

Example script:
```
# Delete Cantaloupe cache on the images container
0 */2 * * * /usr/bin/docker exec isle-images-ld bash -c "find \/usr\/local\/cantaloupe\/cache\/ -maxdepth 6 -mmin +120 -type f -name \"*\" -delete"
```

#### Additional details / screenshots

- There is an open question of which version of Cantaloupe is being used in ISLE that may confuse this issue further and any potential fix.

**Comment by shorock** [comment]
We ran into this (we are working toward a no-token-for-public-views plan so we can hand out nice IIIF URLs, but that's not done yet).

In ours, which is up-to-date with ISLE v1.1.1 at least as far as imageservices, I have

cache.server.source.ttl_seconds = 900

At: https://github.com/Islandora-Collaboration-Group/isle-imageservices/blob/bda1969f885b2664bae8143401b9c6225d41692c/rootfs/etc/confd/templates/imageserv/cantaloupe4.properties.tpl#L424

Also turned the cache.server.derivative.ttl_seconds down to 1 hour.  And at least around here, Cantaloupe is obeying those ttls pretty well and cleaning up.

**Comment by bseeger** [comment]
Thanks for this info @shorock.

**Comment by g7morris** [comment]
@shorock Thanks for this information. Quick question? Have you tested these settings with a large ingest involving Large Images, Books using Internet Archive Book reader , tiffs etc? Anecdotally, I've found that in some cases, large ingests fill up this cache. I'm trying to drill down which process and content type seems to be the culprit, my spider sense tells me it is some kind of tiff, IAB combo? Have you experienced that in your IIIF travels?
