### ISSUE TITLE
Demo ISLE Site Resources: Requesting password prefix change for "Demo ISLE Site"

### ISSUE THREAD

**Issue by dwk2** [Islandora-Collaboration-Group/ISLE#217]
#### Issue description

- The "Demo ISLE Site Resources" (https://islandora-collaboration-group.github.io/ISLE-Documentation/02_installation_demo_site/demo_resources/) lists "Demo ISLE Site" passwords starting with a prefix of `ild_`. The documentation now uses the clearer `demo_` as a prefix for all demo activity. 

##### What's the expected result?

- I'd like the  "Demo ISLE Site" passwords to begin with `demo_`, instead of `ild_`, for consistency.
- I'm unsure about the scope of where those changes must occur within the ISLE setup files.

**Comment by g7morris** [comment]
Hi @dwk2 , 

If you would like the ISLE maintainers to consider this request, I'd recommend that you tag / label this issue with the `ISLE-v.1.1.2` label for review and discussion. I believe there is a meeting next week that this could be added to the list. I'm going to take myself off the Assignees list as the ISLE maintainers will need to review prior to assigning any potential changes.

I can say off hand, [issue #202](https://github.com/Islandora-Collaboration-Group/ISLE/issues/202) should be reviewed and fixed prior to implementing such changes.

Thanks, 
Gavin

**Comment by dwk2** [comment]
Tagged for `ISLE-v.1.1.2`. 
TY for explaining the process for assigning someone. Got it now.

**Comment by dwk2** [comment]
I had thought that this edit would only effect people running the demo, which I believed has much usage now as compared to in 2019 when ISLE was first taking off. Either way, no worries. I understand the risk of breaking changes and I don't want that either. Thanks for the careful analysis.

**Comment by g7morris** [comment]
Closing as "can't fix" from testing learned in ISLE 1.5.5 release
