### ISSUE TITLE
Clean up cantaloupe config files in isle-imageserves

### ISSUE THREAD

**Issue by bseeger** [Islandora-Collaboration-Group/ISLE#226]
#### Issue description
There are some cantaloupe configuration files that need to be cleaned up in the isle-imageservices container.   There are files labeled `cantaloupe` and `cantaloupe4` and there should probably only be one set of files.  

Intent is to remove unused cantaloupe configuration files, to make it clear which ones are used in the system.

**Comment by noahwsmith** [comment]
NB: we definitely want to make sure we land on C4 - C3.x is unsupported and has many known issues.

**Comment by g7morris** [comment]
This was handed by https://github.com/Islandora-Collaboration-Group/isle-imageservices/pull/8 and merged into master. Closing ticket as this fixed.
