### ISSUE TITLE
Add documentation to "Update ISLE"

### ISSUE THREAD

**Issue by dwk2** [Islandora-Collaboration-Group/ISLE#231]
I've added a stub on "install_start_here.md" for how to "Update ISLE".
Hopefully, this will be a straightforward process that is platform agnostic.
1) TODO: Add documentation for how we "Update ISLE" with emphasis on best practices regarding explicitly trashing (or not) the older containers and/or how to note the current version in use to enable a revert (if the new images tragically failed) which might be particularly important on, say, a production server.
2) Need to also cover cases on when or which software needs to be reinstalled (ie git or docker for mac) (due to newer releases being available) on the host server or host laptop. And whether we recommend creating a second instance OR overwriting the original software install.

**Comment by dwk2** [comment]
My initial comment (Aug 7, 2018) at top of page has been fulfilled.

@bookishgirl Do you think it still would be useful to add your two Feb 14, 2019 thoughts above to the documentation? If so, do you still think the Update page (https://islandora-collaboration-group.github.io/ISLE/update/update/) is the best place?

**Comment by bookishgirl** [comment]
I've used this documentation successfully(ish) a few times now so I think my comments are mostly outdated. The one thing that I still struggle with is parsing the merge conflicts - where I can (and should) leave my original code and where I should accept the change. I don't know that there is any easy comment that we could add here to help people with that though.

**Comment by dwk2** [comment]
Okay, I'm going to close this issue. If this issue arises again then my hope is that someone will create a fresh ticket at that time. Thank you @bookishgirl .
