### ISSUE TITLE
Move various Google Docs to .md on Repo

### ISSUE THREAD

**Issue by marksandford** [Islandora-Collaboration-Group/ISLE#234]
Release Process
Maintainers
Discussion:  Is the intention to put the versions of record on this repo, or keep on Google Docs?

**Comment by g7morris** [comment]
I believe this is now a release process updated by the ISLE Maintainers here https://github.com/Islandora-Collaboration-Group/ISLE/tree/main/docs/release-notes Closing ticket as this is ongoing.
