### ISSUE TITLE
Check for consistency for use of variables in commands

### ISSUE THREAD

**Issue by marksandford** [Islandora-Collaboration-Group/ISLE#238]
https://github.com/Islandora-Collaboration-Group/ISLE/issues/116

**Comment by dwk2** [comment]
Hi @McFateM and @SummittDweller : Does this issue remain in need of addressing, or has the documentation evolved sufficiently to have resolved this request? Thanks! - David

**Comment by SummittDweller** [comment]
Hard to say, I've been through the process so many times it's just "muscle memory" anymore.  So, yes, I guess it is resolved at least for me.

**Comment by dwk2** [comment]
Thank you @SummittDweller ! Closing issue.
