### ISSUE TITLE
Update Index and Refactor

### ISSUE THREAD

**Issue by br2490** [Islandora-Collaboration-Group/ISLE#240]
This PR seeks to:

Update the index and associated pages with "getting started" (i.e., server and software dependencies) to reduce complexity and specificity.

This PR also removes the current "CREATE AN ISLANDORA USER" which I acknowledge is an important part of some installations and will reinstate that in another revision (under another topic branch/PR).

**Comment by dwk2** [comment]
2.5 years have passed. I believe this is no longer an issue. I am closing it. If you happen to feel this is in error, please re-open the issue and state why this remains important.
