### ISSUE TITLE
Migration Example User story

### ISSUE THREAD

**Issue by bookishgirl** [Islandora-Collaboration-Group/ISLE#241]
Biggest issue - this is a generic user story. do we want to keep it? will we replace it with a "real" user story?
Secondary issue - can we build a section for user stories apart from the instructions for migration? I find it a little out of place/buried where it is.
Third - if nothing else can we take "example" out of the title? If we want to keep this made-up tale I'd rather we describe it as an examplar at the top of the text and NOT in the title. The optics feel off.

**Comment by dwk2** [comment]
@bookishgirl Three years later and I agree with you. I am still uncomfortable with the unfinished nature, and added overhead of maintaining, these example user stories. They were a good idea, but they'd need a lot of work, IMHO, to have them be useful. I recommend that we delete them entirely. Please comment if you agree/disagree. If you agree, I'll submit a PR for this.

**Comment by bookishgirl** [comment]
I agree!

**Comment by dwk2** [comment]
Closing Issue, now resolved with PR https://github.com/Islandora-Collaboration-Group/ISLE/pull/414
