### ISSUE TITLE
Create space/organization for full release notes

### ISSUE THREAD

**Issue by marksandford** [Islandora-Collaboration-Group/ISLE#245]

**Comment by bseeger** [comment]
There is now a space for release notes in the documentation page.  Does the scope of this ticket go beyond that?    Example: https://islandora-collaboration-group.github.io/ISLE/release-notes/release-1-2-0/

**Comment by g7morris** [comment]
This issue has been solved by the inclusion of the `release-notes` section. New release .md files are added by ISLE maintainers. Closing ticket.
