### ISSUE TITLE
How to PR: Convert google doc to Markdown and post w/ ISLE Documentation

### ISSUE THREAD

**Issue by dwk2** [Islandora-Collaboration-Group/ISLE#247]
#### Issue description
How to PR: Convert google doc to Markdown and post w/ ISLE Documentation
https://docs.google.com/document/d/19eGtaKOgFhog95tXRlrrTj_3f9CA9S3PbR5Adimaaq4/edit#

Still working out if we want to include a condensed version of commands as well.

##### What's the expected result?
- New file for Contributors posted with ISLE Documentation.

**Comment by bseeger** [comment]
This is now converted:  https://github.com/Islandora-Collaboration-Group/ISLE/blob/master/docs/contributor-docs/making-pr-guide.md
