### ISSUE TITLE
A newer docker-compose release is available

### ISSUE THREAD

**Issue by dwk2** [Islandora-Collaboration-Group/ISLE#280]
#### Issue description
A newer release of `docker-compose` is available. 
The [ISLE documentation](https://islandora-collaboration-group.github.io/ISLE/install/host-software-dependencies/#centos) offers this command

```
`curl -L https://github.com/docker/compose/releases/download/1.23.1/docker-compose-`uname -s`-`uname -m`
```

to install docker-compose release 1.23.1 from Nov 2018. I would like to suggest that we test the newest docker-compose release 1.24.1 from June 23, 2019 in our next ISLE release (after 1.1.2).
https://github.com/docker/compose/releases/

##### What's the expected result?

- We will need to test and then update the install/host-software-dependencies/ document for both the sections: ubuntu and centos

**Comment by g7morris** [comment]
@dwk2 Is there any more outstanding work on this or can this ticket be closed?

**Comment by dwk2** [comment]
The only change needed is to update (this single page of documentation only) to change the docker-compose version from 1.23.1 to 1.28.5. If okay to proceed, I can update that and submit it as a PR.

**Comment by g7morris** [comment]
Perhaps we just say something more neutral like endusers can find the latest version at this link https://docs.docker.com/compose/install/ and can follow OS appropriate steps under the Install Compose section. That would save you from having to constantly update the version number. It is more important that folks learn to maintain this for themselves and understand where to go vs the specific version number which as we have found goes stale rather quickly. 

Your thoughts on this?

**Comment by dwk2** [comment]
I like that! I'll add it as a PR.

**Comment by dwk2** [comment]
Added: https://github.com/Islandora-Collaboration-Group/ISLE/pull/413
Closing this issue.
