### ISSUE TITLE
Look at citeproc module in Islandora

### ISSUE THREAD

**Issue by bseeger** [Islandora-Collaboration-Group/ISLE#288]
#### Issue description
Recently there has been a change in how we deal with citeproc in Islandora and we have two backends possible, the newer and bugfixed one is a composer dependency.
https://github.com/Islandora/islandora_scholar/blob/39445ee3de783de3f5d39b4235fe9ada9df15658/modules/citeproc/citeproc.module
So it would be good to document that either A) ISLE ships the old backend or B) people need to customize their install to get the second option.

**Comment by g7morris** [comment]
This was fixed in ISLE release 1.3.0 https://github.com/Islandora-Collaboration-Group/ISLE/issues/271 Closing ticket.
