### ISSUE TITLE
Documentation for previous versions should be more usable

### ISSUE THREAD

**Issue by marksandford** [Islandora-Collaboration-Group/ISLE#297]
#### Issue description
Documentation for previous versions is only available as .md files in local repo

#### For an issue, describe steps to reproduce the issue

All versions/setups

##### What's the expected result?

A user-friendly (non raw-markdown) version of the documentation that retains navigation, etc.

##### What's the actual result?

User only has access to markdown files.

#### Additional details / screenshots

generated HTML, docker service for local env

**Comment by marksandford** [comment]
See PR #336

**Comment by dwk2** [comment]
@marksandford Does your merged PR #336 fully solve this Issue? If so, then this this issue is ready for you to close.
