### ISSUE TITLE
Page for upgrading from version 1.1.2 or prior

### ISSUE THREAD

**Issue by marksandford** [Islandora-Collaboration-Group/ISLE#319]
We need to have a permanent page with instructions on how to upgrade from 1.1.2 or prior, to ensure configs get updated to new model.

**Comment by dwk2** [comment]
@marksandford: I believe this has been completed and the resultant doc page is this: https://islandora-collaboration-group.github.io/ISLE/release-notes/release-1-2-0/

May we close this issue?

**Comment by marksandford** [comment]
Yes, it is.  Thanks!  Closing
