### ISSUE TITLE
Eliminate VirtualBox instructions as it only appears in the `edits hosts file` doc?

### ISSUE THREAD

**Issue by dwk2** [Islandora-Collaboration-Group/ISLE#320]
#### Issue description
May we eliminate VirtualBox instructions as it only appears in the `edits hosts file` doc?
https://islandora-collaboration-group.github.io/ISLE/install/install-demo-edit-hosts-file/

It seems like ISLE is not providing documentation for installing ISLE on VirtualBox except for this old remnant. May I remove the 2 VirtualBox documentation options from that file?

**Comment by marksandford** [comment]
I saw yes, let's remove it, unless someone has a reason to keep it in.

**Comment by dwk2** [comment]
I've got this on my TODO list for next DOCS PR (this week).

**Comment by dwk2** [comment]
This has already been completed. Closing issue.
