### ISSUE TITLE
Test if ":cached" is harmless to all OS's? If so, we can simplify the DOCS

### ISSUE THREAD

**Issue by dwk2** [Islandora-Collaboration-Group/ISLE#322]
#### Issue description
francesca Today at 10:09 AM
Noticing a little discrepancy on Software Dependencies for Local/Mac installation under the "improve performance on Mac OSX:" section - the update to the volumes in the apache section is already all set I think?but with slightly different naming ... on my docker-compose.local.yml my volume path is ./data/apache/html (not ./mnt/html as the documentation suggests) and it is already mapped to "/var/www/html:cached"

david.keiser.clark  1 hour ago
@francesca I see that:
docker-compose.demo.yml shows a path of - isle-apache-data:/var/www/html, while
docker-compose.local.yml shows a path of - ./data/apache/html:/var/www/html:cached
@g7morris May we update and standardize the docker-compose.demo.yml to also include the suffix :cached?
(Is that suffix bad for non-Mac's, like Linux or Windows?)
@francesca If we can eliminate the special Mac instructions for adding :cached, then the difference between the docker volume isle-apache-data and the bind mounted ./data/apache/html becomes a non-issue for users.

g7morris  44 minutes ago
@david.keiser.clark I'm not sure what the impact for the demo will be given that it doesn't bind mount the html directory

g7morris  44 minutes ago
This might work against us in the demo

g7morris  43 minutes ago
Perhaps you could test this and report back please @david.keiser.clark?

david.keiser.clark  43 minutes ago
To clarify, you are suggesting that I test the use of adding ":cached" on a Demo instance? on a Mac, Windows, or both?

david.keiser.clark  42 minutes ago
@g7morris ^

g7morris  38 minutes ago
@francesca Yeah that is odd. Typically only /mnt/ is used on Production and Staging servers in this context.

g7morris  37 minutes ago
That should be updated to something more mac specific like /your_path_to/html:/var/www/html:cached (edited) 

g7morris  36 minutes ago
@david.keiser.clark Now that I'm reading this https://docs.docker.com/docker-for-mac/osxfs-caching/

Docker DocumentationDocker Documentation
Performance tuning for volume mounts (shared filesystems)
Docker 17.04 CE Edge adds support for two new flags to the docker run -v, --volume option, cached and delegated, that can significantly improve the performance of mounted volume access...
Yesterday at 1:42 PM

g7morris  36 minutes ago
I'm not sure if adding that value globally is making sense

g7morris  36 minutes ago
for the demo per se

g7morris  35 minutes ago
For a local, it makes sense for folks doing development

g7morris  34 minutes ago
So even within that documentation there is an additional line for more reading here https://blog.docker.com/2017/05/user-guided-caching-in-docker-for-mac/

Docker BlogDocker Blog
User-guided caching in Docker for Mac - Docker Blog
Learn from Docker experts to simplify and advance your app development and management with Docker. Stay up to date on Docker events and new version announcements!
May 5th, 2017
(5 kB)
https://blog.docker.com/wp-content/uploads/1e51d4bd-c100-42a4-b5b0-ece3f7cedd35-1.jpg

g7morris  33 minutes ago
This :cached: line seems to be very Mac specific

g7morris  33 minutes ago
and for use with bind-mounts

g7morris  33 minutes ago
I'd not recommend we introduce this value into the Demo please

david.keiser.clark  28 minutes ago
@g7morris So I think I hear you saying this:
- Demo: do not use the :cached value at all.
- Local: Use the :cached value ONLY for Macs.
If that is true:
- I can update docs.
- Should I also update the docker-compose.local.yml and docker-compose.test.yml which both currently ship with the :cached value hardcoded?

g7morris  9 minutes ago
I'm not suggesting any of that

g7morris  9 minutes ago
I think leaving the Demo as is please

g7morris  9 minutes ago
And leaving the local as is but perhaps testing if there is any impact on say Windows or Linux

g7morris  8 minutes ago
and then reporting back as needed

g7morris  7 minutes ago
Anecdotally, I can report that it appears leaving in the :cached: in the docker-compose.local.yml and bind-mounting a separate directory for /var/www/html for a Linux laptop seems to have no perceivable ill effect

g7morris  6 minutes ago
However testing would be needed to see what effect using a Docker volume instead of a bind-mount would be?

david.keiser.clark  6 minutes ago
What's a fair test to determine if there is any noticeable effect? (Site up and runs? Ingest?)

g7morris  5 minutes ago
Yes that seems complete and perhaps what happens if you make live minor code edits? (edited) 

g7morris  3 minutes ago
@david.keiser.clark Hopefully that is enough information for you or someone to get started? I need to go back offline now. Thanks. :slightly_smiling_face:

#### URLS with ":cached" instructions
- https://islandora-collaboration-group.github.io/ISLE/install/install-local-new/#step-8-run-islandora-drupal-site-install-script
- https://islandora-collaboration-group.github.io/ISLE/install/install-local-migrate/#step-3-git-clone-the-production-islandora-drupal-site-code
- https://islandora-collaboration-group.github.io/ISLE/install/host-software-dependencies/#step-4-clone-isle-repository

**Comment by gavinmorris** [comment]
this conversation thread is from a different site right?

**Comment by dwk2** [comment]
Sry gavinmorris! We had Slack username and github auto-pulled you in based on that Slack name. 
Feel free to please ignore this Issue :)
I've updated the issue with the correct github username.

**Comment by gavinmorris** [comment]
ok cool, no worries!

**Comment by dwk2** [comment]
Closing this issue. No longer a relevant issue.
