### ISSUE TITLE
Build nano into the Linux image?

### ISSUE THREAD

**Issue by McFateM** [Islandora-Collaboration-Group/ISLE#33]
Can I make a request to please build 'nano' into any Linux images?  My vi skills are practically non-existent and I've butchered more than one file this afternoon.

**Comment by br2490** [comment]
docker has a copy command you can use to retrieve and push files to containers!  I find this makes editing larger docs easier.

`docker ps`  to grab the name of the container (isle-web, isle-solr, isle-fedora, isle-db are our options)

to get a file `docker cp isle-web:/etc/apache2/sites-enabled/sites.conf ~/Desktop/sites.conf` 
to push a file  `docker cp ~/Desktop/sites.conf isle-web:/etc/apache2/sites-enabled/sites.conf `

**Comment by McFateM** [comment]
Thanks Ben.  I think settings.php is one of those files that it does not work on?  I tried this...

```
ma7053:ISLE markmcfate$ docker cp isle-web:/var/www/html/sites/default/settings.php ~/Desktop/settings.php
ma7053:ISLE markmcfate$ docker cp ~/Desktop/settings.php isle-web:/var/www/html/sites/default/settings.php
```
I was able to easily edit the file in between 'docker cp' commands but got this when I tried to write the file back...

`Error response from daemon: Error processing tar file(exit status 1): remove /settings.php: device or resource busy`

Made me wonder if Atom might have a Docker package to assist with this.  Didn't find exactly this but there are some Atom goodies out there that I might look at later.

**Comment by br2490** [comment]
@McFateM  Dangit!  I'm Sorry.   So much for that work around - interesting that file is WO.  Right?

Are you able to: `docker exec -it isle-<whatever> bash` and then `apt update; apt install nano -y`?  Ubuntu should automatically change you editor choice to nano, but if not and you would like to make sure: `update-alternatives –config editor`

**Comment by McFateM** [comment]
Good morning @br2490.  Yes, I was able to open a bash shell and add nano in.

**Comment by g7morris** [comment]
@McFateM A reasonable request for the web image/container. Added nano to installed tools. (via this [commit](https://github.com/Islandora-Collaboration-Group/ISLE/commit/6cc6f4b0c69616c37f073c24a3a0f57c37cc1655))
