### ISSUE TITLE
Drupal/Islandora 8 version

### ISSUE THREAD

**Issue by attiks** [Islandora-Collaboration-Group/ISLE#364]
#### Issue description

What is the best place to track the progress on the Islandora 8 version

I saw https://groups.google.com/forum/#!topic/islandora-isle/S9YO8sRP3Ek but my organization is mainly looking into the dockerized setup.

I've read https://groups.google.com/forum/#!topic/islandora-isle/3kzcPV9wClE and tried https://github.com/Islandora-Devops/islandora-playbook/pull/127 which is looking great.

I also saw the [presentation](https://docs.google.com/presentation/d/1aLLxt65wNnLNmBLutCE7ZhtliD0KR_3YwhUwQS8uR-c/edit#slide=id.g62d2ae815d_0_755) and the microservice approach looks very promising.

**Comment by noahwsmith** [comment]
I suggest joining the ISLE interest group bi-weekly call: https://docs.google.com/document/d/1QZH-JFfroIA8NUFJu2NDwbmKV6ygCY7SjW001g8FeOU/edit#heading=h.bdicubw25j61

Wednesdays 3pm Eastern.

**Comment by fabianderijk** [comment]
I'm looking for the same. For a client of ours we want to use Islandora 8 and Fedora 5 in dockerized setup. I've already read that there is a planning to release the 8 version during or around DrupalCon, but is there already a dev version or something we can test? Or start using during our own development process?

**Comment by noahwsmith** [comment]
The Github repo for the ISLE-8 project is here: https://github.com/Islandora-Devops/isle-dc

Status as of March 18 is that this repo runs Islandora without Fedora. Target for the next 3-4 weeks is add support for Fedora and dependencies. There is also a robust delivery of workflows and tooling that should be merged this week from https://github.com/Islandora-Devops/isle-dc/pull/6

**Comment by g7morris** [comment]
Closing this ticket as paths for the ISLE 8 project have been conveyed. Thanks everyone for the continued interest in ISLE.
