### ISSUE TITLE
Staging install instructions: clarify or improve "commit locally to git"

### ISSUE THREAD

**Issue by bondjimbond** [Islandora-Collaboration-Group/ISLE#365]
#### Issue description

At the ["Edit the '.env' file" stage of the installation instructions](https://github.com/Islandora-Collaboration-Group/ISLE/blob/master/docs/install/install-staging-migrate.md#step-12-on-remote-staging---edit-the-env-file-to-change-to-the-staging-environment), we are told:

> You'll need to add this file and commit it in git to be able to get future updates from ISLE as a process.

> git add .env
> git commit -m "Added the edited .env configuration file for Staging. DO NOT PUSH BACK TO UPSTREAM REPOSITORY - Jane Doe 8/2019"
> This is a suggested warning for users NOT TO push back this configuration change to the main git repository. If that were done it could conflict with other setups.

Following these instructions does not actually prevent `.env` from being pushed back; should we not simply be adding it to `.gitignore` instead?

**Comment by g7morris** [comment]
@bondjimbond You are 100% correct in questioning this and in identifying the proper method. I believe this process was to be included in an upcoming release. I'll make note of this and discuss with the team.

**Comment by g7morris** [comment]
Closing as "fixed" from ISLE 1.5.5 release
