### ISSUE TITLE
Documentation: update the final terminal output of install_solution_packs.sh

### ISSUE THREAD

**Issue by ysuarez** [Islandora-Collaboration-Group/ISLE#396]
#### Issue description

Updating the documentation to reflect the current final terminal output of scripts/apache/install_solution_packs.sh in the following files...

docs/install/install-local-migrate.md
docs/install/install-staging-migrate.md

The current terminal output is listed as:
"Done. 'all' cache was cleared."

Though it should be:
"Drush script finished! ...exiting"

Also, I wonder if install-production-migrate.md is missing a section for running scripts/apache/install_solution_packs.sh

Maybe it is not needed, but I have not reviewed install-production-migrate.md yet.

@marksandford
@g7morris

**Comment by noahwsmith** [comment]
Terrific- thank you!
