### ISSUE TITLE
Error Message needs attention

### ISSUE THREAD

**Issue by DonRichards** [Islandora-Collaboration-Group/ISLE#398]
#### Issue description
Error message is unclear.

#### For an issue, describe steps to reproduce the issue

To understand the this error I looked at the code and found my answer but it's clear this isn't approachable for everyone.
```shell
if [[ ${PWD} == *"User"* ]]; then
...
```

##### What's the expected result?

Better wording to understand what changes are suggested. Some like 
`"ISLE cannot be run from within a child directory under the user profile (~/.../ISLE or %userprofile%/.../ISLE). Please move it to a system directory; something like /vhost/ISLE or /System/Volumes/Data/ISLE"`

Followed by a one liners as to why or point to a doc that explains it.

##### What's the actual result?

```shell
Hello
Docker doesn't support NFS within the 'User' subdirectory.
  Please move your Code/Projects parent directory out to somewhere like /System/Volumes/Data/__.
You will also need to allow Docker access to that directory:
  Docker For Mac > Prefs > Resources > File Sharing > add your parent directory. No need to cache.
make: *** [Makefile:62: fix_mac_nfs] Error 1
```

#### Additional details / screenshots

<img width="805" alt="Screen Shot 2020-12-09 at 10 55 30 AM" src="https://user-images.githubusercontent.com/2738244/101653189-123e7100-3a0d-11eb-8be4-b8bddf94d506.png">

**Comment by noahwsmith** [comment]
@DonRichards this is Born-Digital specific, not ICG:ISLE. The fix_mac_nfs script is just something we use internally.
