### ISSUE TITLE
WARC tools missing from ISLE-apache Dockerfile

### ISSUE THREAD

**Issue by bondjimbond** [Islandora-Collaboration-Group/ISLE#402]
#### Issue description

The WARC tools from https://github.com/internetarchive/warctools need to be added to the Dockerfile in ISLE-apache (https://github.com/Islandora-Collaboration-Group/isle-apache/blob/master/Dockerfile). 

These tools are required to support islandora_solution_pack_web_archive, which depends on `warcfilter` and `warcindex`. These are the default paths to those files:

```
/usr/local/bin/warcfilter
/usr/local/bin/warcindex
```

#### For an issue, describe steps to reproduce the issue

Within the apache container, search for `warcfilter` and `warcindex`; you won't find them. Ingesting an item with the Islandora Web ARChive content model therefore results in -1 Byte derivatives.

#### Additional details / screenshots

![Screen Shot 2020-12-18 at 2 57 27 PM](https://user-images.githubusercontent.com/6069170/102656164-71089680-4141-11eb-9240-b6ab90991ccc.png)

**Comment by noahwsmith** [comment]
@g7morris @bondjimbond I had a few minutes while something else was compiling so I figured out what we needed to add. Gavin had warned me about an unrelated OpenJPEG issue which is preventing this from building fully, but my local testing shows the WarcTools step succeeds.

**Comment by g7morris** [comment]
Hi @bondjimbond

Thanks for this ticket. 

Just an update that I merged in @noahwsmith 's PR https://github.com/Islandora-Collaboration-Group/isle-apache/commit/36f9cdf3aca1d91b628f6d2040647b5b4a468bea to add the WARCTools as directed. 

Recommend that you `docker-compose down` and then `docker-compose pull` to get the newly built images when you have a chance to review and test.

Also @McFateM this might interest you too as I think you are a WARC user. 

Cheers, 
Gavin

**Comment by bondjimbond** [comment]
Thanks!

**Comment by g7morris** [comment]
Closing ticket as resolved.
