### ISSUE TITLE
Documentation update: docs/update/update.md needs "master" changed to "main"

### ISSUE THREAD

**Issue by SummittDweller** [Islandora-Collaboration-Group/ISLE#409]
#### Issue description
This is a documentation change required in `docs/update/update.md`, and maybe elsewhere?  

I'm working through the aforementioned document to update my dg.localdomain instance of ISLE from v1.5.3 to v1.5.4 and found what I believe is a problem with lines 36 and 37.  Those read:

* Pull down the ICG ISLE "master" branch into your Local project's new "isle-update-numberhere" branch:
    * `git pull icg-upstream master`

However, it appears that proper branch name is now `main`, not `master`, so explicitly pulling the `master` branch does not update as expected.  

It looks like the branch naming was changed from `master` to `main` to follow-up with Github's change in mid-2020, but not all of the documentation references to `master` were changed to `main`?  This one seems particularly important since without such a change the procedure won't accomplish what's intended. 

Thanks for making the change in branch names in the first place!

**Comment by g7morris** [comment]
Hi @marksandford or @dwk2 

Is this something that the Documentation team could pick up for the upcoming ISLE release?

Thanks,
Gavin

**Comment by dwk2** [comment]
Yes, I'll take care of it.
David

**Comment by dwk2** [comment]
This is completed. Please see https://github.com/Islandora-Collaboration-Group/ISLE/pull/412
