### ISSUE TITLE
Add rsync to the isle-web image?

### ISSUE THREAD

**Issue by McFateM** [Islandora-Collaboration-Group/ISLE#42]
Sorry to keep making requests.  

I'm working with my local instance of Isle-web and am trying to setup IMI (Islandora Multi Importer) in order to help quickly populate some objects in my test repo.  But rsync is not installed on the image?  I thought it was standard linux fare, but apparently it is not.  

I've just installed it from my bash terminal (sudo apt-get install rsync) and am running an rsync now.  Could we possibly add rsync to the image in the future to eliminate this step?  Thanks.

**Comment by McFateM** [comment]
Agreed and thank you.

**Comment by g7morris** [comment]
Closing ticket. This request has been satisfied with this [commit](https://github.com/Islandora-Collaboration-Group/ISLE/commit/bc27936934609ce22088a145cbc163fc9929b24d) Rsync added to isle-apache image (formerly web)
