### ISSUE TITLE
cache.server.source.ttl_seconds set twice in cantaloupe.properties

### ISSUE THREAD

**Issue by quornicus** [Islandora-Collaboration-Group/ISLE#422]
cache.server.source.ttl_seconds is set twice in cantaloupe.properties, once at line 468 and again at 481. My impression is that cache.server.derivative.ttl_seconds was the intended property for line 481.

**Comment by g7morris** [comment]
Thanks very much for taking the time to spot this!

I've pushed a [fix](https://github.com/Islandora-Collaboration-Group/isle-imageservices/pull/25) which rebuilt and pushed the Docker image with the newly fixed settings. 

Really appreciate your help with this. 

Closing the ticket as fixed.
