### ISSUE TITLE
Staging Migration: Software Dependencies for both Ubuntu and CentOS are missing two steps

### ISSUE THREAD

**Issue by dwk2** [Islandora-Collaboration-Group/ISLE#428]
#### Issue description
1) When I setup my staging server for ISLE7, and add my user to the `docker` group, I get the following error message: "group 'docker' does not exist"
2) When I run `docker ps -a`, I get the following error message: `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

#### Additional details / screenshots
Solution would be to add the following to the [Software Dependencies](https://islandora-collaboration-group.github.io/ISLE/install/host-software-dependencies/#centos) documentation page, for both the Ubuntu and CentOS sections

Create Step 3.5) Create the `docker` group
`sudo groupadd docker`
Create Step 5) Configure Docker to start on boot
```
 sudo systemctl enable docker.service
 sudo systemctl enable containerd.service
```

(Solutions from [Post-installation steps for Linux](https://docs.docker.com/engine/install/linux-postinstall/))

**Comment by g7morris** [comment]
Thanks @dwk2 These steps have now been added as requested.
