### ISSUE TITLE
DockerHub Tags

### ISSUE THREAD

**Issue by dmer** [Islandora-Collaboration-Group/ISLE#43]
Dockerhub Images taggged as:
isle-fedora 3.7.1
isle-fedora 3.8
isle-fedora 3.8.1

isle-solr 4.2
isle-solr 4.6.1
isle-solr 4.10

isle-mysql 5.5
isle-mysql 5.6

isle-apache 2.2
isle-mysql 2.4

**Comment by g7morris** [comment]
Have pushed 

isle-fedora:3.8.1
isle-fedora:latest

isle-solr:4.10.4
isle-solr:latest

isle-mysql:5.6
isle-mysql:latest

isle-apache:2.4
isle-apache:latest

**Comment by g7morris** [comment]
Currently using `alpha2` until approved code merge into master and further testing.

**Comment by g7morris** [comment]
All images are tagged and documented here: https://islandora-collaboration-group.github.io/ISLE-Documentation/06_specifications/specs_docker_containers_images/

isle-fedora:latest, 3.8..1
isle-solr:latest, 4.10.4
isle-mysql:latest, 5.6
isle-apache:latest, 2.4
isle-proxy:latest, 1.13

Closing ticket as now documented.
