### ISSUE TITLE
CentOS 7 build error for apache container

### ISSUE THREAD

**Issue by hamhpc** [Islandora-Collaboration-Group/ISLE#55]
I'm running through the centos instructions and so far they seem to work fine. When I get to the apache container I get this: 

[islandora@islandora-dev ISLE]$ docker-compose build apache
Building apache
Step 1 : FROM ubuntu:14.04 AS ffmpeg_base
ERROR: Service 'apache' failed to build: Error parsing reference: "ubuntu:14.04 AS ffmpeg_base" is not a valid repository/tag
[islandora@islandora-dev ISLE]$

**Comment by g7morris** [comment]
@hamhpc Sadly, I'm unable to replicate this error on our test CentOS 7 server.

`docker-compose build apache` starts the build process asap e.g. 

docker-compose build apache
Building apache
Step 1/31 : FROM ubuntu:14.04 AS ffmpeg_base
 ---> d6ed29ffda6b
Step 2/31 : MAINTAINER "Gavin Morris <gavin@born-digital.com>"
 ---> Running in 60af3bc70f0c
Removing intermediate container 60af3bc70f0c
 ---> ded0068e83f8
Step 3/31 : RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
 ---> Running in 38e34ccb9c47
Removing intermediate container 38e34ccb9c47
 ---> 177f4c2c8269
Step 4/31 : RUN apt-get update
 ---> Running in d8d554747f4e
Get:1 http://security.ubuntu.com trusty-security InRelease [65.9 kB]

Are you still seeing this issue?

**Comment by hamhpc** [comment]
Ok no worries... It might just be me then. I'm going to restart the process with a clean slate and see what happens.

**Comment by hamhpc** [comment]
Ok this is due to using an older version of docker. (I used yum to install it instead of the wget method). Once I had the latest version of docker this works as expected.
