### ISSUE TITLE
ISLE documentation missing required quotations on `uname`

### ISSUE THREAD

**Issue by dwk2** [Islandora-Collaboration-Group/ISLE#57]
(David is submitting this issue on behalf of a colleague who's testing ISLE on AWS Ubuntu 16.04)

Hello all - 
I found this reference to install docker-compose on linux:
https://docs.docker.com/compose/install/#install-compose

It looks like your documentation is missing critical sing quotes which may simply be a formatting issue on your page. 

Here is the command that I used to install docker-compose with the quotes in the correct places:

sudo curl -L https://github.com/docker/compose/releases/download/1.17.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose

Hope it helps,
- Lynna

**Comment by hamhpc** [comment]
Unless Ubuntu or others are different I would tend to think that these will always be the same value?

[root@fedora ~]# uname -m
x86_64
[root@fedora ~]# uname -s
Linux
[root@fedora ~]# 

So maybe it makes better sense to just change the command to sudo curl -L https://github.com/docker/compose/releases/download/1.17.0/docker-compose-Linux-x86_64 -o /usr/local/bin/docker-compose? just a thought. 

And those quotes should be around each uname command like this: 

https://github.com/docker/compose/releases/download/1.17.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose

**Comment by dwk2** [comment]
More edits (see the RED and ORANGE text) are included in this google doc (should be viewable to all)
https://docs.google.com/document/d/1r-I9n8mUhlJ5Z-X9AO-RrikhzH6I8bTPIL25LmtRbxE/edit?ts=5a25a046

**Comment by g7morris** [comment]
@dwk2 Please thank your colleague for their time on this. Very helpful and apologies for the formatting issue. I've gone ahead and incorporated all of the suggested changes from that Gdoc. 
Indeed the backtics were improper and could cause a challenge. 

This [commit](https://github.com/Islandora-Collaboration-Group/ISLE/commit/563f23d950fa6a0257b6a689b15cc410bc15c7d9) has updated this [page](https://islandora-collaboration-group.github.io/ISLE/1_system_process_overview/1_4_testing/alpha_build_guide_linux/)

@dwk2 I'm prepared to close this ticket unless it doesn't match the suggested updates?

**Comment by dwk2** [comment]
Fixed. Thank you!
