### ISSUE TITLE
root password on host

### ISSUE THREAD

**Issue by hamhpc** [Islandora-Collaboration-Group/ISLE#58]
Hi, 
  I was wondering what the root password is for the host? I see in the matrix that under the MySQL container there is this: 

root | islemysqlrootpw2017

I suspect this might also be the root password for the host? Not a big deal as using my kickstart method you can set the root pass when the machine is built (from the configure OS screen). I was just looking for what might have been set already as I would grab that encrypted password and set it in the kickstart script so that it matches up with the matrix.

**Comment by g7morris** [comment]
@hamhpc I don't believe I set any fixed host root password as that is up to the enduser. Certainly we can explain how to do this but I'm not a fan of telling people what root password to use and then documenting it. ;)

**Comment by hamhpc** [comment]
Umm.. not to pick on you but the matrix has a documented "root" password listed (albeit mysql but still ;-p). Overall, you are correct in that they should have this figured out when the VM/host is built. So good point I'll just leave it out and it'll get set when it's built.
