### ISSUE TITLE
post-alpha cleanup and consolidation @ isle-services level

### ISSUE THREAD

**Issue by br2490** [Islandora-Collaboration-Group/ISLE#63]
I think having a viable product takes precedent; to that end I don't believe anything in this ticket needs action now, none of this is a blocker.  

Hi - I was looking through the services.yml and had a few thoughts I'd like to share to the group

I believe because of how large this stack is the naming and organization of the _enduser config and data folders_  ("customize" currently) need to be clearer than they are now.  As an admin who wants to import their site: where is the mysql data folder, drupal data folder, fedora, solr, etc.?  where would I place my config files to override the ISLE defaults for any of those daemons?

the 'data' folder - any data we want to persist.  Should we consider using Docker volumes in consideration of moving and migrating, or replicating?

 Services Level (the folder with the Docker-compose.yml)

- [x]  Could we rename the "Customize" folder to either "Config" or "Data" depending on it's role?  
- [x]  do those files fit into either a "config" or a "data" role?
- [x]  is it at all possible to squash down some of the volumes definitions? e.g.:

```
    - ./customize/fedora/tomcat/server.xml:/usr/local/tomcat/conf/server.xml
    - ./customize/fedora/tomcat/web.xml:/usr/local/tomcat/conf/web.xml
    - ./customize/fedora/tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    - ./customize/fedora/tomcat/logging.properties:/usr/local/tomcat/conf/logging.properties
``` 
to `./customize/fedora/tomcat:/usr/local/tomcat/conf` or would that break things? 

I also hope this highlights my confusion with a folder named 'customize' as you see it's a conf folder.  Maybe I'm thinking to far into it!

Best!

**Comment by g7morris** [comment]
@br2490 I think this ticket can be closed as with the new alpha2 images I've hit all of the requested points above. Okay to close now?

**Comment by br2490** [comment]
👍 Heck yes, Alpha 2 is good.  Closing.
