### ISSUE TITLE
post-alpha cleanup and consolidation @ isle containers level

### ISSUE THREAD

**Issue by br2490** [Islandora-Collaboration-Group/ISLE#64]
I think having a viable product takes precedent; to that end I don't believe anything in this ticket needs action now, none of this is a blocker.  

Hi - I was looking through some of the Dockerfiles and had a few thoughts!

Container Level (subfolders)

I still have an overall folder structure question:  would it be possible for **Container folders** to contain their Dockerfile, and a single consolidated folder for _all_ configs (even if _that_ folder has children, this is especially true on multi-daemon containers).  Reading the Dockerfile it is easier to understand seeing COPY file from a config folder to a destination on the container, or a "lib" folder being copied to the lib location on the container, etc. 

ISLE-MYSQL  I think can be removed from the images entirely and left in the services definition.  Are we maintaining a customized version of MySQL?  I can totes provide an example - this is the easiest way for me.

ISLE-FEDORA  is perhaps the most challenging as it might as well be called "core" and it hosts more than one daemon.  The layers in this box are _incredible_.  :jaw-drop: (needs to be a thing)

ISLE-WEB:   again, lots of layers, but here we're using intermittent builds!  Nice! 

- [x] organize folders in a coherent manner for their containers
- [x] deprecate "MAINTAINER" and use LABELS per Docker.
- [ ] Can ISLE-MY be deprecated?
- [ ] network consideration (should be at the services level, Ben)

I'll update as I go but sorry, these are some of the thoughts now!

**Comment by g7morris** [comment]
@br2490 I've updated all Dockerfiles to use LABELS now via this [commit](https://github.com/Islandora-Collaboration-Group/ISLE/commit/79000b26431ffb105173f4c1da480f39af9b2c12)

The other elements of your original post should be discussed with the steering committee I think given we're in the Alpha stage and I'd prefer a more orderly way of patching, refactoring etc. 

(I do think you have some good points here just think they should be addressed with the group!)

**Comment by br2490** [comment]
I'm closing this ticket as we're well past this and other issues and I'm in favor of a cleaner queue.
