### ISSUE TITLE
docker-compose.yml apache config

### ISSUE THREAD

**Issue by hamhpc** [Islandora-Collaboration-Group/ISLE#65]
Hi.. I'd like to suggest setting the default in the docker-compose.yml to be linux instead of macosx. So the lines: 

#- ./customize/apache/site/linux_settings.php:/var/www/html/sites/default/settings.php
- ./customize/apache/site/macosx_settings.php:/var/www/html/sites/default/settings.php

should get reversed like this: 

- ./customize/apache/site/linux_settings.php:/var/www/html/sites/default/settings.php
#- ./customize/apache/site/macosx_settings.php:/var/www/html/sites/default/settings.php

Since we'll need to have special circumstances for macosx (adding /etc/hosts and change the docker-compose.yml) I'd say let the linux settings be on by default so the linux builds won't need to update the docker-compose.yml. I'd imagine most of the time we'll be doing linux in the enterprise over macosx ;-).

**Comment by br2490** [comment]
Great points.  I'm not sure what the difference of those files is, or what they purport to do differently from one another.

The Dockerfile specifies Ubuntu as the based for the HTTPD.

I think we should explore docker compose more in-depth;  for example, the "hostname" and "domainname" (or it might just be domain) are two configurable options in compose files that may resolve MacOS issues.

**Comment by g7morris** [comment]
@hamhpc Agreed. Have updated the docker-compose.yml file to this effect via this [commit](https://github.com/Islandora-Collaboration-Group/ISLE/commit/79000b26431ffb105173f4c1da480f39af9b2c12)

@br2490 Difference is very minor and potentially laughable.

macos settings.php uses http://apache for the $base_url value
linux uses http://islandora-docker.com for the $base_url value

Totally open to suggestions on a new technique.

**Comment by g7morris** [comment]
otherwise ready to close this ticket!

**Comment by hamhpc** [comment]
Sounds good to me. I guess for a new technique I'd need to ponder it some but overall I'd say close away now that Linux is default ;-).
