### ISSUE TITLE
sudo install method

### ISSUE THREAD

**Issue by hamhpc** [Islandora-Collaboration-Group/ISLE#68]
This might be a little bit simpler to set up sudo for islandora user. This is what I have been doing that works but I'm not sure if this is just a CentOS thing or sudo thing universally (meaning not sure it's the same in Ubuntu). Anyhow here's the method:

echo "islandora   ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/islandora

That's it =). No messing with visudo!

**Comment by g7morris** [comment]
@hamhpc Good tip. Should have done this in the first place. 

I've changed the documentation to this suggested effect. (via this [commit](https://github.com/Islandora-Collaboration-Group/ISLE/commit/79000b26431ffb105173f4c1da480f39af9b2c12) Closing ticket.
