### ISSUE TITLE
fedora container error

### ISSUE THREAD

**Issue by hamhpc** [Islandora-Collaboration-Group/ISLE#70]
I'm getting this on the latest install.....

[root@localhost ISLE]# docker-compose up -d fedora
isle-mysql is up-to-date
Creating isle-fedora ... 
Creating isle-fedora ... error

ERROR: for isle-fedora  Cannot create container for service fedora: invalid mode: /etc/apache2/sites-available/site.conf

ERROR: for fedora  Cannot create container for service fedora: invalid mode: /etc/apache2/sites-available/site.conf
ERROR: Encountered errors while bringing up the project.

**Comment by hamhpc** [comment]
This is an error on my behalf. I was in the wrong test server when I issued this. You'll get this if it's already built.

**Comment by hamhpc** [comment]
Ok maybe I was wrong again. I just started it again on a new host and I am getting this here too: 

<snip>
Step 39/40 : EXPOSE 80 8080
 ---> Running in d6e0f4b1c963
Removing intermediate container d6e0f4b1c963
 ---> b976392eaaef
Step 40/40 : CMD ["/usr/local/tomcat/bin/runservices.sh", "run"]
 ---> Running in 5bee021a00c2
Removing intermediate container 5bee021a00c2
 ---> 60637b088ee9
Successfully built 60637b088ee9
Successfully tagged islandoracollabgroup/isle-fedora:latest
[root@islandora-dev ISLE]# docker-compose up -d fedora
isle-mysql is up-to-date
Creating isle-fedora ... 
Creating isle-fedora ... error

ERROR: for isle-fedora  Cannot create container for service fedora: invalid mode: /etc/apache2/sites-available/site.conf

ERROR: for fedora  Cannot create container for service fedora: invalid mode: /etc/apache2/sites-available/site.conf
ERROR: Encountered errors while bringing up the project.
[root@islandora-dev ISLE]#

**Comment by hamhpc** [comment]
I just noticed there is a space in front of this in the docker-compose.yml....


      - ./customize/fedora/apache/site.conf:/etc/apache2/sites-available/site.conf

once I fixed this it started working.

**Comment by g7morris** [comment]
@hamhpc Yup silly dev error on my part. Space got put into code. Apologies for the issue. Have removed this via [commit](https://github.com/Islandora-Collaboration-Group/ISLE/commit/17f02a8f402dcc79c21b077c0fe5a9e2dae098a7)
