### ISSUE TITLE
ISLE documentation: missing "apt install curl" 

### ISSUE THREAD

**Issue by lynnawilliams** [Islandora-Collaboration-Group/ISLE#71]
I'm testing the islandora install process for David Keiser-Clark on a virtualbox client running ubuntu 16.04.3.  Apparently curl is not installed by default on this version of ubuntu and therefore, people may need to give the command:

apt install curl

Before running the command:

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

I can't remember if I saw this error in either the Google Cloud or Amazon Cloud services Ubuntu install that I did earlier in the week.

In case it helps, I have attached a screen capture.
![curlnotinstalled](https://user-images.githubusercontent.com/26227609/33775336-0afb8cc8-dc0c-11e7-9151-fd5965c3f096.jpeg)

**Comment by g7morris** [comment]
@lynnawilliams Agreed. That's not nice to encounter. Have since updated the server install requirements to include curl via this [commit](https://github.com/Islandora-Collaboration-Group/ISLE/commit/17f02a8f402dcc79c21b077c0fe5a9e2dae098a7)
