### ISSUE TITLE
ISLE Build on Ubuntu on Virtualbox - Fedora won't come up

### ISSUE THREAD

**Issue by lynnawilliams** [Islandora-Collaboration-Group/ISLE#74]
Running Ubuntu 16.04.3 in VirtualBox 5.2.2 on Mac OS 10.12.6 ...

docker-compose up -d fedora 
returns an error of "Cannot create container for service fedora: invalid bind mount spec ..."

See attached screen shot for complete error
![fedoranotup](https://user-images.githubusercontent.com/26227609/33783689-c2205eb4-dc2b-11e7-912d-970e97d3a31b.jpeg)

I definitely did not have this error when building this on the google cloud compute service.

**Comment by g7morris** [comment]
@lynnawilliams Thanks for testing this and apologies for the delay.

@hamhpc Noticed this behavior as well in issue [#70](https://github.com/Islandora-Collaboration-Group/ISLE/issues/70)

From @hamhpc 's [comment](https://github.com/Islandora-Collaboration-Group/ISLE/issues/70#issuecomment-350348624)

> I just noticed there is a space in front of this in the docker-compose.yml....

  - ./customize/fedora/apache/site.conf:/etc/apache2/sites-available/site.conf
once I fixed this it started working.

My response on the commnet

Yup silly dev error on my part. A space got put into code/line. Apologies for the issue. Have removed this via [commit](https://github.com/Islandora-Collaboration-Group/ISLE/commit/17f02a8f402dcc79c21b077c0fe5a9e2dae098a7)

Please close ticket once testing has finished.

**Comment by lynnawilliams** [comment]
This seems to have fixed the issue.  Closing the ticket.
