### ISSUE TITLE
Install and enable views_ui

### ISSUE THREAD

**Issue by McFateM** [Islandora-Collaboration-Group/ISLE#83]
Finding that while the views module is installed and enabled, views_ui is not.  This makes Drupal views difficult to configure and use in an ISLE build.  At Grinnell, and elsewhere I suspect, views is a critical element.

Please modify the site make or install scripts to include views_ui.  Thanks.

**Comment by g7morris** [comment]
@McFateM I've added this request to all install shell scripts on the new-dev2 branch via this [commit](https://github.com/Islandora-Collaboration-Group/ISLE/commit/4706cbb3f1c856a7e1ee3f9140ceb7c5aa082603). Will merge into master post Alpha testing. Closing ticket.
