### ISSUE TITLE
Modify documentation for creating the initial system specs

### ISSUE THREAD

**Issue by dwk2** [Islandora-Collaboration-Group/ISLE#86]
For the ISLE Steering Committee to document:

I discovered today a flaw in our (Williams) initial server setup. I received a vm that allocated our 4TB of storage on a mount associated with "/opt/isle", when it should clearly be "/opt".  I had not bothered to check the mount, so this fracked the install.

This mistake caused us to run out of space (obviously). We should document this very precisely to prevent others from running out of space, by having them setup their mount correctly on "/opt".

**Comment by g7morris** [comment]
@dwk2 Good call and apologies that you had to go through that. I've updated the mvpspecs.md file in the docs section warning about proper volume allocation on the `new-dev2` branch with this [commit](https://github.com/Islandora-Collaboration-Group/ISLE/commit/da9ec58142e302c0c001f54a2615c13a3ba27d08). It is a rough draft and I expect to produce more specific guidance for endusers to avoid these types of issues and to educate on proper storage strategy. Please feel free to wordsmith the heck out of it if I've fallen short in this initial effort. Closing ticket as I've now created the initial system specs doc with boilerplate language that should be modified post Alpha testing.
