### ISSUE TITLE
3 small fixes needed in ISLE installation process

### ISSUE THREAD

**Issue by dwk2** [Islandora-Collaboration-Group/ISLE#94]
1) When turning on the fedora container, the pretty green "done" text is listed one time, but the declarative "Creating isle-fedora ... " is listed twice. Ideally, only show a single output of "Creating isle-fedora ... done"; if that's not possible, then at least add the word "done" following the second "Creating isle-fedora ... " statement:
[islandora@isle-dev ISLE]$ docker-compose up -d fedora
Creating isle-fedora ... done
Creating isle-fedora ...

2) Similar issue as #2, above for "apache" container:
[islandora@isle-dev ISLE]$ docker-compose up -d apache
Creating isle-apache ... done
isle-fedora is up-to-date
Creating isle-apache ...

3) Typing the correct admin username (islandora_docker_admin) and pwd results in this error message:
* http://islandora-docker.com/node?destination=node
* Not Found
* The requested URL /node was not found on this server.
* Apache/2.4.29 (Ubuntu) Server at islandora-docker.com Port 80

THIS HAPPENS BECAUSE: the homepage of my newly installed site (http://isle-dev.williams.edu/) has a "submit" button that is redirecting to http://islandora-docker.com/node. 
NOTE that I had not changed my /etc/hosts file; I believe that the ISLE installation should not know about islandora-docker.com at all. There must still be a lingering reference somewhere, right?

**Comment by g7morris** [comment]
@dwk2 

Issues 1 & 2 are Docker-Compose giving output. I cannot control or modify that. Why two lines? Not clear to me. 

3. As we've changed to using isle.localdomain from islandora-docker.com, I'm unable to reproduce this behavior. Additionally currently using your Alpha, I'm also unable to reproduce this behavior. I'll leave this ticket open in the hopes that we can find the challenge. I'll make a point of retesting in future Alphas builds etc.

**Comment by g7morris** [comment]
@dwk2 Not sure what I'm doing (if anything) as:
a) I am currently unable to reproduce the doubling behavior at the present
b) current behavior I see in your Alpha is green only output 
c) I don't have control over what Docker & Docker-Compose spit out as stdout or messages sadly so I can't edit this messaging though that would be brilliant!
d) Issue #3 might be related to what we found earlier with your Alpha test. Check $base_url.
e) `islandora-docker.com` is no longer and isle-localdomain is. All image related information can be pulled from dockerhub.com using `alpha2` tagged images and the `new-dev2` branch on this repo. Documentation to be updated and forthcoming to this effect.

**Comment by br2490** [comment]
@dwk2 - Good point, maybe we should document #1 and #2 in docs.   

This is normal Docker behavior and the creation (and continual recreation) of containers is okay: no panic.  Containers are mutable (stuff happens in a container) and in a stack those containers rely on each other;  when one is changed or modified in docker-compose or build, all other services that depend on it are also recreated or noted as "up-to-date" if those changes impact them.  

The best use example is when you have a working stack, navigating to your docker-compose folder (or passing it with `docker-compose -f /path/to/islandorastack.yml`) and doing `docker-compose stop` and then `docker-compose up -d` _very literally_ checks upstream (if your compose is set to :latest or any 'branch'), pulls any updated **images**, uses your compose to mount and load your content into the new images now running as containers and you've just updated the entire stack in two presses of enter!  YMMV.

**Comment by marksandford** [comment]
Is this still a documentation issue?
