### ISSUE TITLE
location of the docs? 

### ISSUE THREAD

**Issue by hamhpc** [Islandora-Collaboration-Group/ISLE#98]
It looks like the original start of documentation is the docs folder within the master ISLE repo. I believe now that it has been moved into a gh-pages branch for the documentation. Should the docs folder get removed to avoid getting outdated documentation?

**Comment by br2490** [comment]
Resolved by new documentation repository @ https://github.com/Islandora-Collaboration-Group/ISLE-Documentation

@hamhpc please close this ticket if you believe this has been appropriately addressed by the new repository?

**Comment by g7morris** [comment]
Closing ticket as @br2490 has indicated where the new location is.
